/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d5e3ff",
        "on-primary-fixed-variant": "#930007",
        "on-tertiary-container": "#f8f9ff",
        "on-primary-container": "#fff7f6",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#003061",
        "surface-container": "#201f1f",
        "secondary": "#c8c6c5",
        "outline": "#af8782",
        "on-tertiary-fixed-variant": "#004689",
        "primary-container": "#e50914",
        "surface-container-highest": "#353534",
        "secondary-container": "#474746",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#410001",
        "on-tertiary-fixed": "#001b3c",
        "on-secondary": "#313030",
        "tertiary": "#a7c8ff",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb4aa",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "error": "#ffb4ab",
        "tertiary-container": "#0072d7",
        "on-surface-variant": "#e9bcb6",
        "surface": "#131313",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-primary": "#c0000c",
        "on-secondary-container": "#b7b4b4",
        "outline-variant": "#5e3f3b",
        "primary-fixed": "#ffdad5",
        "inverse-on-surface": "#313030",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#ffb4aa",
        "surface-tint": "#ffb4aa",
        "on-primary": "#690003",
        "surface-dim": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#a7c8ff",
        "background": "#131313",
        // Keep netflix colors as backup
        netflixRed: "#E50914",
        netflixBlack: "#141414",
        netflixGray: "#181818",
        netflixLightGray: "#B3B3B3",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "1rem",
        "margin-desktop": "4rem",
        "container-max": "1440px",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        "display-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-bold": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-base": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "800"}],
        "label-bold": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-base": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
